export const FETCH_GITHUB_INFO = 'FETCH_GITHUB_INFO'
export const FETCH_GITHUB_INFO_SUCCESS = 'FETCH_GITHUB_INFO_SUCCESS'
export const FETCH_GITHUB_INFO_FAILURE = 'FETCH_GITHUB_INFO_FAILURE' 
export const CLEAR_INFO = 'CLEAR_INFO'
